version: "3.8"

services:  
  backend:
    image: 2214yj/3-tier-application-backend:nolb
    ports:
      - 8081:8081
    depends_on:
      - database
    links:
      - database
    restart: always

  database:
    image: mariadb:10.9
    volumes:
      - SampleDatabaseData:/var/lib/mysql
      - ./database_build/mysql:/etc/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=DOCKERTEST
      - MYSQL_ROOT_PASSWORD=qwerty1234
    restart: always

  frontend:
    image: 2214yj/3-tier-application-frontend:nolb
    ports:
      - 80:35001
    restart: always

volumes:
  SampleDatabaseData:

